### PR TITLE
KLC fixes

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR fixes KLC issues for many of the JST connectors

- Added Fab layer
- Fixed line width
- Added extra REF** to F.Fab layer
- Better pin-1 identification

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@jkriege2 if you get a chance :)

**Comment by jkriege2** [comment]
Hi!

just scanning through them:
1. At least in `JST_EH_S10B-EH_10x2.50mm_Angled` I found F.SilkS actiavted for pads ... could you check all the others (as batch) too?
2. Several footprints have SilkS-width 0.15mm instead of 0.12mm, e.g. 'JST_SH_SM20B-SRSS-TB_20x1.00mm_Angled'
3. Some are missing F.Fab (e.g. `JST_SH_SM20B-SRSS-TB_20x1.00mm_Angled`)
4. just a though: Some have a quite complex drawing on F.SilkS ... wouldn't that be better placed on F.Fab?

best,
JAN

**Comment by SchrodingersGat** [comment]
1. Fixed
2. Fixed
3. The SH scripts need updating, are you ok to merge this and deal with that later? I did not write these scripts so I'd need to investigate

**Comment by jkriege2** [comment]
Hi!

ad 3) Yes, can do

But some still have 0.15mm SilkS: `JST_SFH_SM02B-SFHRS-TF_02x1.80mm_Angled, JST_PH_S9B-PH-SM4-TB_09x2.00mm_Angled, JST_PH_S9B-PH-K_09x2.00mm_Angled, JST_PH_S8B-PH-SM4-TB_08x2.00mm_Angled, JST_PH_S8B-PH-K_08x2.00mm_Angled, JST_PH_S7B-PH-SM4-TB_07x2.00mm_Angled, JST_PH_S7B-PH-K_07x2.00mm_Angled, JST_PH_S6B-PH-SM4-TB_06x2.00mm_Angled, JST_PH_S6B-PH-K_06x2.00mm_Angled, ..., JST_LEA_SM02B-LEASS-TF_02x1.80mm_Angled, `
Best,
JAN

**Comment by SchrodingersGat** [comment]
LEA connector has been fixed.

The PH connectors are being fixed in:

* https://github.com/KiCad/Connectors_JST.pretty/pull/31
* https://github.com/KiCad/Connectors_JST.pretty/pull/30

So I think this should be ok to merge now?

**Comment by jkriege2** [comment]
OK!

Thanks for all the work 

JAN

**Pull request merged**
