### PR TITLE
Added SUR series connectors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
References:
http://www.jst-mfg.com/product/detail_e.php?series=246
http://www.jst-mfg.com/product/pdf/eng/eSUR.pdf

### CODE REVIEW

**Comment by odurc** [comment]
Hey @SchrodingersGat lets follow https://github.com/KiCad/kicad-library/issues/368 to check how to naming the files.

**Comment by SchrodingersGat** [comment]
Hey @ricardocrudo  I've removed the _SMT suffix from these connectors and fixed all KLC

**Comment by pointhi** [comment]
please adjust the courtyard clearance to 0,5mm

**Comment by SchrodingersGat** [comment]
Done

**Comment by pointhi** [comment]
please recheck the silkscreen outline. When I look onto the datasheet, there is something really misalign.

**Comment by SchrodingersGat** [comment]
@pointhi how about now?

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
