### PR TITLE
JST-PH THT side entry acording to new KLC 

### PR DESCRIPTION
**Pull request by poeschlr**
Changes for new KLC:
- silk line width=0.12mm, 
- fab outline with width=0.1mm, 
- reference on fab with height = 2mm

Datasheet: http://www.jst-mfg.com/product/pdf/eng/ePH.pdf

Old footprint:
tht_s2b_old

New footprint:
tht_s2b_new

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @poeschlr thanks for the contribution here.

All these JST footprints are script-generated, and so it will be easier to keep the script updated than modifying all the files individually.

I shall update the scripts shortly (note that the KLC has also been updated too)

**Comment by SchrodingersGat** [comment]
See comments for https://github.com/KiCad/Connectors_JST.pretty/pull/31 :)

**Comment by poeschlr** [comment]
As far as i see, the merge conflicts are because the silkscreen has been removed from the pads. This is also included in my commit.
jst_ph_s2b-ph-k_02x2 00mm_angled

**Comment by poeschlr** [comment]
I'm not sure about the pin 1 marker on the silkscreen. Does anybody have a better idea on how one could make the pin 1 marker for this connector?

Also should i move the reference on f.fab a bit downwards?

**Comment by SchrodingersGat** [comment]
Here is how I have been indicating pin-1 on the Fab layer for other connectors:

p1

Similar, except the triangle points *towards* the first pad. Also, it is a fair bit smaller (~1x1mm)

Please fix the conflicts too - force your new files to override the old ones.

**Comment by poeschlr** [comment]
Ok i reduced the size of the fab layer pin 1 mark and changed the pin 1 mark on the silk layer to a line covering the full length of the pad.
jst_ph_s2b-ph-k_02x2 00mm_angled_fab_t2


Alternatively i could also generate the fab pin 1 mark similar to the one you used in your connectors. But the other ph connectors already have the version i use here. (You merged them yesterday.)
jst_ph_s2b-ph-k_02x2 00mm_angled_fab_t3

**Comment by SchrodingersGat** [comment]
I like the second option better - can you update to match that?

**Comment by poeschlr** [comment]
Should we update the smd variants as well such that they have the same pin 1 marking?

**Comment by SchrodingersGat** [comment]
If you have the time :)

**Comment by SchrodingersGat** [comment]
Thanks, these look great :)

**Pull request merged**
