### PR TITLE
Added JWPF series connectors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
JWPF THT connectors

http://www.jst-mfg.com/product/pdf/eng/eJWPF1.pdf

Some dimensions were missing from datasheet so the alignment was checked against 3D models downloaded from JST website.

a

b

c

d

e

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
There's a KLC error as the NPTH mounting hole is located on the silkscreen. However this is a non-solder hole and is drawn according to the datasheet so it should be OK.

**Comment by evanshultz** [comment]
@SchrodingersGat 
Thanks! These look mostly OK. A couple notes:
1. The refdes silkscreen is placed different only single- and double-row footprints.
1. I'd like a nicer pin 1 mark on silk, but this connector doesn't lend itself to a nice solution.
1. The Travis errors seem OK to me. Probably this check shouldn't apply to NPTHs.

**Comment by evanshultz** [comment]
@SchrodingersGat Will you address any of these items I mentioned, or should I merge? None of them are significant, but I wanted to at least bring up what I saw for your review.

**Comment by SchrodingersGat** [comment]
@evanshultz I have fixed point 1, not sure what improvements can be made for 2, and I think 3 should be ignored for now (and fixed in the KLC scripts)

I have also now updated the part naming scheme to match the new format

1. `Vertical` instead of `Straight`
1. `1x03_P2.00mm` instead of `3x2.00mm`

**Comment by evanshultz** [comment]
@SchrodingersGat Great. But I found one new issue:
image

**Comment by SchrodingersGat** [comment]
Thanks Evan should be fixed now

**Comment by evanshultz** [comment]
@SchrodingersGat 
I'm back from vacation; sorry for the delay here.

The footprints all look OK to me now. Are there any updates needed for the script at https://github.com/pointhi/kicad-footprint-generator/pull/60?

**Comment by SchrodingersGat** [comment]
Nope, I tweaked that last one by hand, it would be too much work to adjust the script to accommodate that one case.

**Comment by evanshultz** [comment]
Alright then. Thanks!

**Pull request merged**
