### PR TITLE
Added ZE series connectors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
References:
http://www.jst-mfg.com/product/detail_e.php?series=470
http://www.jst-mfg.com/product/pdf/eng/eZE.pdf

### CODE REVIEW

**Comment by odurc** [comment]
Hey @SchrodingersGat lets follow https://github.com/KiCad/kicad-library/issues/368 to check how to naming the files.

**Comment by SchrodingersGat** [comment]
ze top entry

An example of the ZE series top-entry connector

**Comment by SchrodingersGat** [comment]
ze top entry

Example of the -1D series (top entry with boss, NPTH mouting hole)

**Comment by SchrodingersGat** [comment]
ze top entry

Example of the top-entry SMT version of the ZE connectors

**Comment by SchrodingersGat** [comment]
(all these footprints have been generated using the python scripting tool by @pointhi which I have forked here: https://github.com/SchrodingersGat/kicad-footprint-generator)

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
