### PR TITLE
JST improvements

### PR DESCRIPTION
**Pull request by SchrodingersGat**
This PR adds a number of key improvements for the JST connectors
- Connector outline added to Fabrication layer
- Silkscreen improvements
- Better designation of pin-1

Connectors in the following series have been updated:
- ZE
- PUD
- XH
- EH
- J2100
- SUR
- GH
- SHL

### CODE REVIEW

**Comment by poeschlr** [comment]
Is it on purpose that none of this connectors (except pud series) have a pin 1 marker on the fab layer?

The PUD series has a lot of artwork on the fab layer. I think i read in some other pull request that you don't want that. Should this be moved to the silk layer?
screenshot from 2016-09-09 15-25-03

And the reference field of XH-B02B is on top of the pin 1 marker. Maybe move this a bit.

**Comment by SchrodingersGat** [comment]
HI @poeschlr the reason that none of the other connectors have the Fab indicator is that I have neglected to add it! I've been going through old scripts and trying to bring improvements where I see them, but I didn't notice this one.

I'll make the fixes to all these connectors. I'll also fix the issues with the Fab artwork on the PUD series. Thanks.

**Comment by SchrodingersGat** [comment]
I have added pin-1 markings to the Fab layer for all parts. I have also moved that artwork to the silkscreen layer for the offending PUD parts.

**Comment by poeschlr** [comment]
Looks good now.

**Comment by pointhi** [comment]
`JST_ZE` (and probably other one as well) are missing Solder Mask for NTPH holes

**Pull request closed without merging**
