### PR TITLE
[fix] Corrected pin numbers for JST GH top-entry connectors

### PR DESCRIPTION
**Pull request by jordiorlando**
According to the datasheet, pin no. 1 is located on the right for top-entry headers and on the left for side-entry headers. As this library currently stands, it is very easy to accidentally flip the polarity of a cable.

### CODE REVIEW

**Comment by jordiorlando** [comment]
It seems all the files generated with kicad-footprint-generator have incorrect line-endings. Should I fix that and force-push a correct commit to re-trigger the Travis checks?

**Comment by pointhi** [comment]
Dear 0xdec,

the Datasheet orientation is not important for footprint design. KiCad Library Footprint are following general standards, named [Kicad-Library-Convention](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention), which are moreover based on industrial standards.

Orientation of the footprint is one of those rules specified by the KLC, and is based on an industrial standard named IPC-7351:

```
6.2 Pad 1 is on the left first, then at the top, except at the top for PLCC (IPC-7351).
```

**Comment by jordiorlando** [comment]
Oh, I see. I only noticed this issue because I have a mixture of top and side-entry headers on some PCBs I just designed, and after ordering them I noticed that they would be incorrect. For example, if I have a 4-pin top-entry and a 4-pin side-entry connector, each with connections [VCC, SCL, SDA, GND], and I try to connect a cable between them, it will connect VCC to GND and so forth, which is obviously quite bad. Furthermore, if I design a 4-pin connector into the schematic with a JST-GH side-entry connector in mind and then decide to switch to a top-entry connector, I have to remember to switch all of my schematic connections. You can see how this might be prone to error.

**Comment by jordiorlando** [comment]
A potential solution is to rotate the JST-GH top-entry connectors by 180 degrees so that PIN 1 is still on the left.

**Comment by jordiorlando** [comment]
@SchrodingersGat any thoughts on this?

**Comment by SchrodingersGat** [comment]
The scripts should be updated such that Pin-1 is on the left. This will require an updated to the [scripts](https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/JST). I haven't had a chance to look at this closely yet, but I shall soon.

I recently used the GH connectors on a production board so I will have a very close look. Hopefully this weekend.

**Comment by jordiorlando** [comment]
I updated the scripts to match the datasheets, but that means that the footprints go against the KiCad Library Convention. If this is acceptable, then pointhi/kicad-footprint-generator#30 should work just fine. If not, I can change the PR to instead rotate the connector 180deg such that Pin 1 is still on the left to follow convention, while also remaining accurate to the datasheet.

**Comment by SchrodingersGat** [comment]
Pin-1 must be located on the left, so please make that change if you have not done so already.

**Comment by 0xdec** [comment]
I'm fixing it now, but I just noticed that running the latest kicad-footprint-generator master without any changes seems to number the pins starting at zero instead of one. Is this a known issue?

**Comment by jordiorlando** [comment]
Updated so that Pin 1 is on the left, and fixed pointhi/kicad-footprint-generator#30 as well.

**Pull request merged**
