### PR TITLE
J2000 series

### PR DESCRIPTION
**Pull request by SchrodingersGat**

### CODE REVIEW

**Comment by pointhi** [comment]
From the datasheet, this is a double row connector.

I would suggest you to change the size attribute accordingly:

`_06x2.50mm_Straight` --> `_02x03x2.50mm_Straight`

**Comment by SchrodingersGat** [comment]
@pointhi - thanks for the tip, I wasn't sure how to proceed on this. Changes have been made as suggested.

**Comment by pointhi** [comment]
Please apply KLC:

```
checking module: JST_J2000_B06B-J21DK-GG_2x03x2.50mm_Straight
  Violating Rule 10.1
    Footprint name must match its filename. (.kicad_mod files).
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
checking module: JST_J2000_B08B-J21DK-GG_2x04x2.50mm_Straight
  Violating Rule 10.1
    Footprint name must match its filename. (.kicad_mod files).
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
checking module: JST_J2000_B10B-J21DK-GG_2x05x2.50mm_Straight
  Violating Rule 10.1
    Footprint name must match its filename. (.kicad_mod files).
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
checking module: JST_J2000_B12B-J21DK-GG_2x06x2.50mm_Straight
  Violating Rule 10.1
    Footprint name must match its filename. (.kicad_mod files).
  Violating Rule 10.4
    Value is filled with footprint name and is placed on the fabrication layer.
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
```

Please also consider rule 6.2:

```
6.2. Pad 1 is on the left first, then at the top, except at the top for PLCC (IPC-7351).
```

**Comment by SchrodingersGat** [comment]
Fixed the 3D model names too:

https://github.com/KiCad/kicad-library/pull/250

**Comment by SchrodingersGat** [comment]
@ricardocrudo removed the _PTH suffix, checked KLC

**Comment by pointhi** [comment]
Please fix KLC:

```
6.2. Pad 1 is on the left first, then at the top, except at the top for PLCC (IPC-7351).
```
- recheck the Mounting holes (the copper foil land seems to small for some components)
- rearange reference and value text (like done for most other footprints)

**Comment by SchrodingersGat** [comment]
j2100-top

Fixed J2100 top-entry type

**Comment by SchrodingersGat** [comment]
side

Fixed the side-entry type also @pointhi (with your fantastic script, and a few choice additions ;) )

Please let me know if this is now up to scratch

**Comment by SchrodingersGat** [comment]
Whoops, mounting holes weren't NPTH - fixed!

**Comment by pointhi** [comment]
can I ask why you use NTPH pads instead of normal ones?
It seems the mounting pin is made from metal, so it would make sense to have the hole trought-plated

also please realign the text field for the top entity type, so it doesn't cross the courtjard

the rest looks fine to me

**Comment by SchrodingersGat** [comment]
@pointhi an oversight. I've fixed this now.

**Comment by pointhi** [comment]
The datasheet says the copper foil land of the side entry type has a diameter of 3.4mm. Apart from that I don't see any remaining issues.

**Comment by SchrodingersGat** [comment]
Done

**Comment by pointhi** [comment]
when you follow datasheet recomendations, only the copper foild land of the side entry type has a diameter of 3,4mm.

Now there is a KLC issue for the Straight connectors:

```
checking module: JST_J2100_B06B-J21DK-GG_2x03x2.50mm_Straight
  Violating Rule 6.5
    Silkscreen is not superposed to pads, its outline is completely visible after board assembly, uses
    0.15mm line width and provides a reference mark for pin 1. (IPC-7351).
```

I would recommend using 3mm copper foil land for the straight connectors, as described in the datasheet

**Comment by SchrodingersGat** [comment]
good point, whoops!

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
