### PR TITLE
Added JST EH series connectors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Reference:
http://www.jst-mfg.com/product/detail_e.php?series=58
http://www.jst-mfg.com/product/pdf/eng/eEH.pdf

### CODE REVIEW

**Comment by odurc** [comment]
Hey @SchrodingersGat lets follow https://github.com/KiCad/kicad-library/issues/368 to check how to naming the files.

**Comment by SchrodingersGat** [comment]
All EH-series connectors (Straight and Angled) have been added, generated with kicad_mod.py
All KLC pass

**Comment by pointhi** [comment]
There is a KLC issues with all JST_EH footprints:

```
checking module: JST_EH_B02B-EH-A_02x2.50mm_Straight_PTH
  Violating Rule 10.1
    Footprint name must match its filename. (.kicad_mod files).
```

**Comment by SchrodingersGat** [comment]
@pointhi  I think you've got an outdated version of these. The latest version (merged) doesn't have the _PTH suffix and has no KLC issue. Cheers

**Comment by SchrodingersGat** [comment]
Same issue as https://github.com/KiCad/Connectors_JST.pretty/pull/8

I'll issue a new PR and reference.

**Comment by SchrodingersGat** [comment]
https://github.com/KiCad/Connectors_JST.pretty/pull/20

**Pull request merged**
