### PR TITLE
Added SHL series JST connectors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
http://www.jst-mfg.com/product/detail_e.php?series=233

Footprints generated using kicad footprint generator - https://github.com/pointhi/kicad-footprint-generator

### CODE REVIEW

**Comment by pointhi** [comment]
the generated files have some incorrect formating : `CR CR LF` instead of `CR LF`, which causes an empty line between every normal line.

I think this could be a Windows specific bug of my generator script, because I always specified the newline explicit with `\r\n`

**Comment by SchrodingersGat** [comment]
@pointhi yep ok I've fixed this, changed the script to spit out "\n" only

**Comment by SchrodingersGat** [comment]
_SMT suffix has been removed, and passes all KLC checks

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
