### PR TITLE
JST-PH THT top entry acording to new KLC

### PR DESCRIPTION
**Pull request by poeschlr**
Changes for new KLC:
- silk line width=0.12mm, 
- fab outline with width=0.1mm, 
- reference on fab with height = 2mm

Datasheet: http://www.jst-mfg.com/product/pdf/eng/ePH.pdf

Old footprint:
tht_b2b_old

New footprint:
tht_b2b_new

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @poeschlr thanks for the contribution here.

All these JST footprints are script-generated, and so it will be easier to keep the script updated than modifying all the files individually.

I shall update the scripts shortly (note that the KLC has also been updated too)

**Comment by poeschlr** [comment]
@SchrodingersGat 
These footprints are also generated with the scripts by @pointhi 
I have not yet merged them to his repo because the footprints have not been merged.

Also could you elaborate more on my klc problems? (I made them for the new klc. At least for the one that is under: https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention revision 1.1 from october 2016)
This would help me because i might find time to update my phoenix contact scripts shortly.

**Comment by poeschlr** [comment]
By the way this scipts did not use the modtree. I recreated them for that.
Here the branch if you are interested: (I made the changes 4 month ago so i did not remember everything when i wrote my previous comment.)
https://github.com/poeschlr/kicad-footprint-generator/tree/JST_PH_TO_MODTREE/scripts/JST

**Comment by SchrodingersGat** [comment]
@poeschlr ah ok if you have scripted these then this is a different issue - especially if you are using @pointhi  scripts!

Ok, I shall run you through the issues I have and then will re-open your PRs :)

( The reason for my uncertainty is that I am currently re-working all my old JST scripts to conform to modern KLC. I incorrectly thought that the PH ones were mine but I think that @pointhi wrote those ).

Looking over your improvements here, they look really good.

Check out the draft for the [new KLC](https://github.com/SchrodingersGat/kicad-library/wiki/KLC) (not yet live).

In particular, refer to 7.3 and 7.4.

The RefDes should be on **both** the silkscreen and fab layers, and should be 1mm text size. It appears in your script that you already have provision for this! Great!

I *think* that all that is needed is to reduce the text size for the RefDes?

**Comment by poeschlr** [comment]
Do i understand the new rules correctly and the main reference should be on the silk layer. The reference on the fab layer would then be a user text with %R

**Comment by poeschlr** [comment]
As far as i see, the merge conflicts are because the silkscreen has been removed from the pads. This is also included in my commit.
jst_ph_b2b-ph-k_02x2 00mm_straight

**Comment by SchrodingersGat** [comment]
It will be easier if you can fix these conflicts - force the new files to overwrite the old ones entirely.

**Comment by poeschlr** [comment]
> It will be easier if you can fix these conflicts - force the new files to overwrite the old ones entirely.

What's the best way to do this?
I would merge the master of this repo into my branch but tell git to take my files. (or copy my files over the changes from the merge stuff if i mess up.)
Is there a better way?

**Comment by SchrodingersGat** [comment]
Best way is (as you suggest) to merge /master into your branch, and then select "Use my files" where conflicts occur.

Other option is to do the following:

a) Delete these files, commit
b) Merge kicad/master
c) Delete the conflicting files again, commit
d) Re-run your scripts to get fresh files.

I think the first option is easiest?

**Comment by poeschlr** [comment]
I did the merge with a mergetool but in the end did not trust the result and re-run my scripts and used these freshly generated files.

**Comment by SchrodingersGat** [comment]
The 16-pin connectors are giving errors:

```
checking module: JST_PH_B16B-PH-K_16x2.00mm_Straight
  Violating Rule 10.4
  Violating Rule 10.5
  Violating Rule 10.8
  Violating Rule 6.5
  Violating Rule 6.9
checking module: JST_PH_B16B-PH-SM4-TB_16x2.00mm_Straight
  Violating Rule 10.4
  Violating Rule 10.5
  Violating Rule 10.8
  Violating Rule 6.5
  Violating Rule 6.9
```

**Comment by poeschlr** [comment]
My scripts had an off by one error. 
I'm not sure if i started with smd side entry. This series has no 16 pin connector (This would mean it was a copy paste error). 
I'm inclined to believe that i forgot that range(2,16) generates the series 2,3,...,15 (This would mean i was lucky that i didn't generate the non existing 16pin version of the smd side entry connector.)

**Comment by SchrodingersGat** [comment]
Great work, thanks :)

**Pull request merged**
