### PR TITLE
Add VH series, update NV series

### PR DESCRIPTION
**Pull request by evanshultz**
Datasheet: http://www.jst-mfg.com/product/pdf/eng/eVH.pdf

All are script-generated which I will submit after this is done.

With the NV series getting merged from https://github.com/KiCad/Connectors_JST.pretty/pull/49, I moved on to the VH series. There are several types of headers in this family, so it was quite a bit more complex. I found that JST provides 3D models, which I used to find dimensions that weren't given. I did not make footprints missing any pins, since pins can be removed in Pcbnew. A few notes:
1. Please provide feedback on F.Fab and F.SilkS pin 1 marks for anged connectors.
1. I did not draw a bump for the latch of the shrouded headers.
1. I reflected in silk what can be seen from the top, "covering up" lower elements of the header. OK?
1. I copied the style of the angled pin headers where possible, since those were created recently.

Image of the smallest, middle, and largest in each family since there are so many footprints:
image

### CODE REVIEW

**Comment by evanshultz** [comment]
Removed the NV series updates to fix branch conflicts.

**Comment by evanshultz** [comment]
Can somebody take a look at these footprints?

**Comment by SchrodingersGat** [comment]
Evan these look good, I would make one request.

As per the discussion at https://github.com/KiCad/kicad-library/issues/1447 we have decided that we should name the connectors `Horizontal` and `Vertical` rather than `Angled` and `Straight`. Are you able to make these changes to your script?

**Comment by evanshultz** [comment]
Sure! I wanted to touch this again since the VH and VH-B (left right two series) are using different scripts, and I should combine them anyway.

Two questions:
- The BxxPS series has a notch in the F.Fab corner for pin 1. Is that OK? Would a triangle inside the body be better?
- I just realized the SxxP series doesn't have a pin 1 mark on F.Fab. Ideas on how to do that?

**Comment by SchrodingersGat** [comment]
### BxxPS

Yes I think a triangle would look better.

### SxxP

A triangle inside the body shold work well here too, I think.

Note - the pin-1 marker on the silkscreen should be moved further from pin-1 pad. Currently it will be removed by the solder mask expansion. 0.3mm clearance from the pad edge should do it.

**Pull request closed without merging**
