### PR TITLE
JST-PH SMT side entry acording to new KLC | And correction of pad positions/sizes

### PR DESCRIPTION
**Pull request by poeschlr**
Changes for new KLC:
- silk line width=0.12mm,
- fab outline with width=0.1mm, 
- reference on fab with height = 2mm

Also corrected the pad sizes and positions.

Datasheet: http://www.jst-mfg.com/product/pdf/eng/ePH.pdf

Old footprint:
smt_s2b_old
New footprint:
smt_s2b_new

Details for wrong pad sizes/positions:
Red measurements from datasheet: http://www.jst-mfg.com/product/pdf/eng/ePH.pdf
smt_s2b_wrong_pads

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @poeschlr thanks for the contribution here.

All these JST footprints are script-generated, and so it will be easier to keep the script updated than modifying all the files individually.

I shall update the scripts shortly (note that the KLC has also been updated too)

**Comment by SchrodingersGat** [comment]
See comments for https://github.com/KiCad/Connectors_JST.pretty/pull/31 :)

**Comment by poeschlr** [comment]
jst_ph_s2b-ph-sm4-tb_02x2 00mm_angled

**Comment by SchrodingersGat** [comment]
Please add "smd" attribute into these files - otherwise they look great :)

**Comment by SchrodingersGat** [comment]
Thanks!

**Pull request merged**
