### PR TITLE
Added connectors from AUH series

### PR DESCRIPTION
**Pull request by SchrodingersGat**
http://www.jst-mfg.com/product/pdf/eng/eAUH.pdf

auh

3D files are here: https://github.com/KiCad/kicad-library/pull/250

### CODE REVIEW

**Comment by pointhi** [comment]
- Please fix courtyard positioning (0,5mm distance from pads/outline))
- Please adjust Pin 1 marker (nearer the pad, same design and spacing for both footprints)

**Comment by SchrodingersGat** [comment]
Made those adjustments. Let me know if they are OK

**Comment by pointhi** [comment]
can you tell me, why your pad dimensions differ from the one described in the datasheet?

**Comment by SchrodingersGat** [comment]
Probably because I read the datasheet wrong. Good catch.

**Comment by pointhi** [comment]
`JST_AUH_BM05B-AUHKS-GA-TB` looks fine, but please realign the courtyard of `JST_AUH_BM03B-AUHKS-GA-TB`.

the rest looks fine

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
