### PR TITLE
Added JST GH series connectors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
References:
http://www.jst-mfg.com/product/detail_e.php?series=105
http://www.jst-mfg.com/product/pdf/eng/eGH.pdf

### CODE REVIEW

**Comment by odurc** [comment]
Hey @SchrodingersGat lets follow https://github.com/KiCad/kicad-library/issues/368 to check how to naming the files.

**Comment by SchrodingersGat** [comment]
KLC compliance for all GH series connectors

**Comment by SchrodingersGat** [comment]
@ricardocrudo  any notes on these? They're passing KLC, and the naming scheme has been adjusted to meet how @pointhi  is naming the connectors

**Comment by odurc** [comment]
Thanks Oliver, they are great.

**Comment by pointhi** [comment]
There is a KLC issues with all JST_GH footprints:

```
checking module: JST_GH_BM02B-GHS-TBT_02x1.25mm_Straight_SMT
  Violating Rule 10.1
    Footprint name must match its filename. (.kicad_mod files).
```

**Comment by SchrodingersGat** [comment]
@pointhi I think you may be working from an outdated version of those files. The _SMT suffix is no longer in the part name (and I don't get the KLC violation when I check)

**Comment by pointhi** [comment]
look: https://github.com/KiCad/Connectors_JST.pretty/blob/master/JST_GH_SM03B-GHS-TB_03x1.25mm_Angled.kicad_mod

```
(module JST_GH_SM03B-GHS-TB_03x1.25mm_Angled_SMT (layer F.Cu) (tedit 56C991C6)
```

**Comment by SchrodingersGat** [comment]
Ah I see. Looks like this was merged with that issue and I've fixed the issue locally. I'll issue a new PR and reference it here.

**Comment by SchrodingersGat** [comment]
https://github.com/KiCad/Connectors_JST.pretty/pull/20

**Pull request merged**
