### PR TITLE
Added PUD 10-way vertical thru-hole connector

### PR DESCRIPTION
**Pull request by SchrodingersGat**
References:
http://www.jst-mfg.com/product/detail_e.php?series=471
http://www.jst-mfg.com/product/pdf/eng/ePUD.pdf

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
KLC compliance for all PUD series connectors

**Comment by SchrodingersGat** [comment]
@ricardocrudo  I removed the _PTH suffix from these connectors and all KLC pass

**Comment by pointhi** [comment]
please fix the following issues:
- replace the mechanical holes with the correct NTPH pad
- recheck the courtyard distances, especially for the side types

**Comment by SchrodingersGat** [comment]
@pointhi I've completely reworked the PUD series, adding all the top-entry and side-entry types.

**Side Entry:**
side

**Top Entry:**
top

**Comment by pointhi** [comment]
please move the value text of the Straight connectors a little bit out of the courtyard.

the rest looks fine to me

**Comment by pointhi** [comment]
Please recheck the position of the mounting holes of the side entry type.

The rest looks fine to me.

**Comment by SchrodingersGat** [comment]
good catch!

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
