### PR TITLE
Update names of NV/VH, minor fixes for horizontal VH

### PR DESCRIPTION
**Pull request by evanshultz**
Since so many footprint names changed due to the request at https://github.com/KiCad/Connectors_JST.pretty/pull/50, I started a new branch. Continuing on from there...

@SchrodingersGat Thanks for the feedback. All are done.

I took this opportunity to rename my NV series footprints as well.

Datasheets:
- http://www.jst-mfg.com/product/pdf/eng/eNV.pdf
- http://www.jst-mfg.com/product/pdf/eng/eVH.pdf

Images:
image
image
image
image
image

### CODE REVIEW

**Comment by evanshultz** [comment]
Why can't I delete to NV footprints with old names and add the new ones at the same time? After considerable nonsense, I uploaded the existing files from master to re-create the `...Straight` NV footprints; I'll delete them in a separate PR once this is merged.

**Comment by SchrodingersGat** [comment]
Evan if you are unable to remove the incorrect files, I'd prefer you close this PR and issue a new one with just the correct files :)

**Comment by evanshultz** [comment]
I got it straightened out. Not sure why it was so much trouble, but this PR is all good.

I'm sometimes forgetful, but hopefully I would have left a note if there were lingering issues and it wasn't ready to merge. :)

**Comment by evanshultz** [comment]
But if you prefer, I can close this and start a new PR.

**Comment by SchrodingersGat** [comment]
No problem, this is all good. Thanks for your contribution :)

**Pull request merged**
