### PR TITLE
JST-PH SMT top entry acording to new KLC

### PR DESCRIPTION
**Pull request by poeschlr**
Changes for new KLC:
- silk line width=0.12mm
- fab outline with width=0.1mm
- reference on fab with height = 2mm

Datasheet: http://www.jst-mfg.com/product/pdf/eng/ePH.pdf

Old footprint:
smt_b2b_old

New footprint:
smt_b2b_new

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @poeschlr thanks for the contribution here.

All these JST footprints are script-generated, and so it will be easier to keep the script updated than modifying all the files individually.

I shall update the scripts shortly (note that the KLC has also been updated too)

**Comment by SchrodingersGat** [comment]
See comments for https://github.com/KiCad/Connectors_JST.pretty/pull/31 :)

**Comment by poeschlr** [comment]
jst_ph_b2b-ph-sm4-tb_02x2 00mm_straight

**Comment by SchrodingersGat** [comment]
You have removed the "smd" attribute from these files - please add that back in to the script :)

**Comment by SchrodingersGat** [comment]
Nice work, thanks for your efforts :)

**Pull request merged**
