### PR TITLE
Added JST XH series connectors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
References:
http://www.jst-mfg.com/product/detail_e.php?series=277
http://www.jst-mfg.com/product/pdf/eng/eXH.pdf

### CODE REVIEW

**Comment by BenediktSeidl** [comment]
It looks like your pin numbers are in the wrong order. I've tried to get the info from the datasheet, but it seems like it's never explicitly mentioned how the pins are numbered, so I took a picture.

jst_xh_6_vs_7

**Comment by SchrodingersGat** [comment]
Ah, good catch thanks @BenediktSeidl

**Comment by odurc** [comment]
Hey @SchrodingersGat lets follow https://github.com/KiCad/kicad-library/issues/368 to check how to naming the files.

**Comment by SchrodingersGat** [comment]
All XH connectors now passing KLC

**Comment by pointhi** [comment]
- Please look into KLC rule 6.2: 

```
6.2. Pad 1 is on the left first, then at the top, except at the top for PLCC (IPC-7351).
```

### JST_XH_BxB-XH-A_xxx2.50mm_Straight_PTH
- Please look into KLC rule 6.7:

```
6.7. Courtyard clearance is 0.25mm except for components smaller than 0603 at 0.15mm, connectors, SMD canned capacitors and crystals at 0.5mm and BGA at 1.0mm. (IPC-7251, IPC-7351B)
```

#### JST_XH_B2B-XH-A_02x2.50mm_Straight_PTH
- Pin 1 marker differs from the other footprints Straight footprints

### JST_XH_SxB-XH-A_xxx2.50mm_Angled_PTH
- you could remove the arrow from the footprint. (And probably replacing the number with an arrow)

#### JST_XH_S2B-XH-A_02x2.50mm_Angled_PTH
- Pin 1 marker is wrong

## General
- Multiple visible pin1 marker at the side doesn't make sense for me. They only uses space which could be used for other components by default. In my personal view, I personally prefere arrows instead of numbers (explicity pointing to the pin, numbers can probably interfer with other silkscreen references). But let the other maintainers decide.
- It seems your footprints are hand crafted. It's only a suggestion, but using scripts would help you creating bunches of similar footprints and improving them in a slip. For example, I created my jst connectors using a self written library: [pointhi/kicad-footprint-generator](https://github.com/pointhi/kicad-footprint-generator)

**Comment by SchrodingersGat** [comment]
Hi @pointhi - thanks for your input. I've made changes as suggested.

Regarding footprint generation, I've started using your generator already - however most of the footprints I've uploaded thus far have either been taken from http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm (and subsequently edited) or are based on my old libraries that I've been bringing (slowly) towards KLC compliance.

If I were to start again, the footprint generator would be way easier and quicker. I'll certainly be using it for any future footprints I make...

Cheers

**Comment by odurc** [comment]
@SchrodingersGat I've removed _PTH (BTW, should be THT) and _SMT suffixes for while.  Could you please update your other PRs. Thank you.

**Comment by SchrodingersGat** [comment]
@ricardocrudo done for this repo, and for the 3D models also

**Comment by pointhi** [comment]
please fix this KLC issues:

```
6.2. Pad 1 is on the left first, then at the top, except at the top for PLCC (IPC-7351).
```

 (I think you rotated exactly the wrong footprints.)

---

```
6.7. Courtyard clearance is 0.25mm except for components smaller than 0603 at 0.15mm, connectors, SMD canned capacitors and crystals at 0.5mm and BGA at 1.0mm. (IPC-7251, IPC-7351B)
```

---

And probably also rearange the reference and value text (one above and at the bottom of the footprint)

**Comment by SchrodingersGat** [comment]
xh

XH series top entry have been fixed now.

**Comment by pointhi** [comment]
- please recheck the pad size: http://www.ipc.org/committee/drafts/1-13_d_7251WD1.pdf (page 12). It's a bit to small.
- and also look if you can rearange `REF**` for the 2 pin connector

the rest looks fine to me

**Comment by SchrodingersGat** [comment]
I've bumped up the pad size @pointhi and fixed REF*\* for 02-pin

**Comment by pointhi** [comment]
thanks for your contribution

**Pull request merged**
